// <auto-generated />
namespace stitalizator01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bet_isLocked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bet_isLocked));
        
        string IMigrationMetadata.Id
        {
            get { return "201704121406494_bet_isLocked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
